### ISSUE TITLE
Not Updated to the develop branch

### ISSUE THREAD

**Issue by DevilIris** [bitfocus/companion-module-evertz-quartz#2]
Hello Guys this module is not merging with the develop branch.

@Julusian Can you merge the last version with the last PR with Salvos?

Thank you!

**Comment by josephdadams** [comment]
The module will need to be updated to the companion v3 api before it can get added.

**Comment by DevilIris** [comment]
@josephdadams Can you please add the tag or release a new version so it can updated changes of salvos? And we can pull it to the new version of legacy?

**Comment by llamafilm** [comment]
I haven't had time to update the module for v3.  Feel free to contribute a PR.

**Comment by josephdadams** [comment]
@DevilIris we can't do anything further with this module until it is upgraded to the Companion v3 API.

https://github.com/bitfocus/companion-module-base/wiki/Upgrading-a-module-built-for-Companion-2.x
